// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrRp6zI7sPabtMFsKMLqwtHgklGedPbR8',
    appId: '1:292633186914:web:0d6115e87182b9fbdf373b',
    messagingSenderId: '292633186914',
    projectId: 'kinquest-af379',
    authDomain: 'kinquest-af379.firebaseapp.com',
    storageBucket: 'kinquest-af379.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQUyv3dG_4j2NITGesdymHRfsuPNjyMQ',
    appId: '1:292633186914:android:6134d1e467a2b75bdf373b',
    messagingSenderId: '292633186914',
    projectId: 'kinquest-af379',
    storageBucket: 'kinquest-af379.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOl-JchJZDLIIwwloGZa110n5ks9mydzQ',
    appId: '1:292633186914:ios:880a9e6fcde89bc7df373b',
    messagingSenderId: '292633186914',
    projectId: 'kinquest-af379',
    storageBucket: 'kinquest-af379.firebasestorage.app',
    iosBundleId: 'com.example.kinquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOl-JchJZDLIIwwloGZa110n5ks9mydzQ',
    appId: '1:292633186914:ios:880a9e6fcde89bc7df373b',
    messagingSenderId: '292633186914',
    projectId: 'kinquest-af379',
    storageBucket: 'kinquest-af379.firebasestorage.app',
    iosBundleId: 'com.example.kinquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrRp6zI7sPabtMFsKMLqwtHgklGedPbR8',
    appId: '1:292633186914:web:b9dc3d88f5604563df373b',
    messagingSenderId: '292633186914',
    projectId: 'kinquest-af379',
    authDomain: 'kinquest-af379.firebaseapp.com',
    storageBucket: 'kinquest-af379.firebasestorage.app',
  );
}
